export enum AchievementCode {
    CURIOUS_10 = 'CURIOUS_10',
    PERSISTENT_15 = 'PERSISTENT_15',
    DEDICATED_20 = 'DEDICATED_20',
    CONSTANT_5 = 'CONSTANT_5',
    UNSTOPPABLE_10 = 'UNSTOPPABLE_10',
    PRECISE_5 = 'PRECISE_5',
    EXPERT_10 = 'EXPERT_10',
    MASTER_15 = 'MASTER_15',
    PERFECTIONIST = 'PERFECTIONIST',
    EARTHLY_GOD = 'EARTHLY_GOD',
    EXPLORER = 'EXPLORER',
    COLLECTOR = 'COLLECTOR'
}
