export enum AchievementCode {
    // Respuestas
    RESPONDER_10 = 'RESPONDER_10',
    RESPONDER_15 = 'RESPONDER_15',
    RESPONDER_20 = 'RESPONDER_20',

    // Racha
    RACHA_3 = 'RACHA_3',
    RACHA_6 = 'RACHA_6',
    RACHA_9 = 'RACHA_9',

    // Precisión
    PRECISION_5 = 'PRECISION_5',
    PRECISION_10 = 'PRECISION_10',
    PRECISION_15 = 'PRECISION_15',

    // Otros
    PERFECCIONISTA = 'PERFECCIONISTA',
    MAESTRO = 'MAESTRO',
    EXPLORADOR = 'EXPLORADOR',
    COLECCIONISTA = 'COLECCIONISTA',
}
